# Generated by Django 4.2.30 on 2026-07-08 03:32

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gyn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('is_verified_patient', models.BooleanField(default=True)),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('helpful_count', models.IntegerField(default=0)),
                ('reply_status', models.CharField(choices=[('Pending', 'Pending'), ('Replied', 'Replied')], default='Pending', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='booking_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
