# Generated by Django 4.2.30 on 2026-07-09 08:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gyn', '0002_review_alter_appointment_booking_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutEarning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(help_text='Patient ya Client ka naam', max_length=100)),
                ('amount', models.IntegerField(help_text='Consultation Fee (in ₹)')),
                ('status', models.CharField(choices=[('Completed', 'Completed (Active Earning)'), ('Pending', 'Pending (Awaiting Settlement)'), ('Withdrawn', 'Withdrawn (Payout Processed)')], default='Completed', max_length=20)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
