# Generated by Django 4.2.30 on 2026-07-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyn', '0003_payoutearning'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard Pricing', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('call_base', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('call_fee_pct', models.DecimalField(decimal_places=2, default=12, max_digits=5)),
                ('call_tax_pct', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('video_base', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('video_fee_pct', models.DecimalField(decimal_places=2, default=12, max_digits=5)),
                ('video_tax_pct', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('chat_base', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('chat_fee_pct', models.DecimalField(decimal_places=2, default=12, max_digits=5)),
                ('chat_tax_pct', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('clinic_base', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('clinic_fee_pct', models.DecimalField(decimal_places=2, default=12, max_digits=5)),
                ('clinic_tax_pct', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('nurse_base', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nurse_fee_pct', models.DecimalField(decimal_places=2, default=12, max_digits=5)),
                ('nurse_tax_pct', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
