# Generated by Django 4.2.30 on 2026-07-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyn', '0004_pricingconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('avatar_emoji', models.CharField(blank=True, help_text='Jaise 🦇, 🦖, 👻', max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('Pregnant', 'Pregnant'), ('Postpartum', 'Postpartum'), ('Planning', 'Planning'), ('Not Pregnant', 'Not Pregnant'), ('No Show', 'No Show'), ('Drama Queen', 'Drama Queen')], default='Planning', max_length=20)),
                ('risk_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
