# Generated by Django 4.2.30 on 2026-07-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyn', '0005_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_type', models.CharField(choices=[('ZONE 01', 'Primary Location'), ('ZONE 02', 'Secondary Location')], default='ZONE 01', max_length=20)),
                ('area_name', models.CharField(blank=True, help_text='e.g. COD (Kanpur Nagar)', max_length=255, null=True)),
                ('pincode', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=100)),
                ('service_radius', models.IntegerField(default=12)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
