# Generated by Django 4.2.30 on 2026-07-17 06:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gyn', '0007_reviewreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='helpful_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
